version: '3.1'

services:

  db:
    container_name: mariadb_11
    image: mariadb:11
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MARIADB_USER: ${MYSQL_DB_USERNAME}
      MARIADB_PASSWORD: ${MYSQL_DB_PASSWORD}
      MARIADB_ROOT_HOST: ${MYSQL_DB_HOST}
      MARIADB_DATABASE: ${MYSQL_DB_DATABASE}
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"
      interval: 5s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MARIADB_INIT}:/docker-entrypoint-initdb.d

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ${WORKDIR_LOCAL}:${WORKDIR_CONTAINER}
      - ${NGINX_LOCAL}:${NGINX_CONTAINER}
    healthcheck:
      test: "curl -f localhost:80"
      interval: 5s
      timeout: 5s
      retries: 20

  php:
    container_name: php_8
    build:
      context: ./docker/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ${WORKDIR_LOCAL}:${WORKDIR_CONTAINER}
    working_dir: ${WORKDIR_CONTAINER}

  rabbitmq:
    container_name: test_rabbitmq
    build:
      context: ./docker/rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  ch_server:
    image: yandex/clickhouse-server
    platform: linux/amd64
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - ch_ntw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ${CLICKHOUSE_INIT}:/docker-entrypoint-initdb.d

networks:
  ch_ntw:
    driver: bridge
